/*===========================================================================
    FName C++ declarations exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if !ENUMS_ONLY
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#if !defined(__GAMEFRAMEWORK_NAMES_H__) || defined(NAMES_ONLY)

#ifndef __GAMEFRAMEWORK_NAMES_H__
#define __GAMEFRAMEWORK_NAMES_H__
#endif

#ifndef AUTOGENERATE_NAME
#define DEFINED_NAME_MACRO
#define AUTOGENERATE_NAME(name) extern FName GAMEFRAMEWORK_##name;
#endif


AUTOGENERATE_NAME(ActivateBehavior)
AUTOGENERATE_NAME(AddToMobileInput)
AUTOGENERATE_NAME(AdjustViewOffset)
AUTOGENERATE_NAME(AILog_Internal)
AUTOGENERATE_NAME(AllowableDestinationFor)
AUTOGENERATE_NAME(ClearLatentAnimation)
AUTOGENERATE_NAME(ClientPlayMovie)
AUTOGENERATE_NAME(ClientStopMovie)
AUTOGENERATE_NAME(CloseAllMenus)
AUTOGENERATE_NAME(CloseMenuScene)
AUTOGENERATE_NAME(CreateNewAgent)
AUTOGENERATE_NAME(CreateSpawner)
AUTOGENERATE_NAME(DecrementCustomerCount)
AUTOGENERATE_NAME(DrawDebug)
AUTOGENERATE_NAME(FillCrowdSpawnInfoItem)
AUTOGENERATE_NAME(FinishedTargetRotation)
AUTOGENERATE_NAME(FireDeathEvent)
AUTOGENERATE_NAME(FlushAgents)
AUTOGENERATE_NAME(FlushAllAgents)
AUTOGENERATE_NAME(GeneratePathToActor)
AUTOGENERATE_NAME(GetActionString)
AUTOGENERATE_NAME(GetCameraWorstCaseLoc)
AUTOGENERATE_NAME(GetDebugVerboseText)
AUTOGENERATE_NAME(GetDesiredFOV)
AUTOGENERATE_NAME(GetDumpString)
AUTOGENERATE_NAME(GetRealPosition)
AUTOGENERATE_NAME(HandleBehaviorEvent)
AUTOGENERATE_NAME(HandlePotentialAgentEncounter)
AUTOGENERATE_NAME(IncrementCustomerCount)
AUTOGENERATE_NAME(InitMenuScene)
AUTOGENERATE_NAME(InitNavigationHandle)
AUTOGENERATE_NAME(InternalPaused)
AUTOGENERATE_NAME(InternalPopped)
AUTOGENERATE_NAME(InternalPrePushed)
AUTOGENERATE_NAME(InternalPushed)
AUTOGENERATE_NAME(InternalResumed)
AUTOGENERATE_NAME(InternalTick)
AUTOGENERATE_NAME(KillAgent)
AUTOGENERATE_NAME(ModifyPostProcessSettings)
AUTOGENERATE_NAME(NotifyCrowdAgentInRadius)
AUTOGENERATE_NAME(NotifyCrowdAgentRefresh)
AUTOGENERATE_NAME(NotifyPathChanged)
AUTOGENERATE_NAME(NotifySeePlayer)
AUTOGENERATE_NAME(OnAnimEnd)
AUTOGENERATE_NAME(OnDoubleTapDelegate)
AUTOGENERATE_NAME(OnInputTouch)
AUTOGENERATE_NAME(OnPostDrawZone)
AUTOGENERATE_NAME(OnPreDrawZone)
AUTOGENERATE_NAME(OnPreviewTouch)
AUTOGENERATE_NAME(OnProcessInputDelegate)
AUTOGENERATE_NAME(OnProcessSlide)
AUTOGENERATE_NAME(OnSceneTouch)
AUTOGENERATE_NAME(OnTapDelegate)
AUTOGENERATE_NAME(OnTouch)
AUTOGENERATE_NAME(OnTouchNotHandledInMenu)
AUTOGENERATE_NAME(OpenMenuScene)
AUTOGENERATE_NAME(OverlappedActorEvent)
AUTOGENERATE_NAME(PickSpawnPoint)
AUTOGENERATE_NAME(PlayIdleAnimation)
AUTOGENERATE_NAME(PostRender)
AUTOGENERATE_NAME(PrioritizeSpawnPoints)
AUTOGENERATE_NAME(PropagateViralBehaviorTo)
AUTOGENERATE_NAME(ReachedDestination)
AUTOGENERATE_NAME(ReachedPrecisePosition)
AUTOGENERATE_NAME(RefreshKismetLinks)
AUTOGENERATE_NAME(RenderMenus)
AUTOGENERATE_NAME(SetCurrentDestination)
AUTOGENERATE_NAME(StopBehavior)
AUTOGENERATE_NAME(StopIdleAnimation)
AUTOGENERATE_NAME(Tick)
AUTOGENERATE_NAME(UpdateFocusPoint)
AUTOGENERATE_NAME(UpdateIntermediatePoint)
AUTOGENERATE_NAME(UpdateShadowSettings)
AUTOGENERATE_NAME(UpdateSpawner)
AUTOGENERATE_NAME(WaitForGroupMembers)
AUTOGENERATE_NAME(WarmupPause)

#ifdef DEFINED_NAME_MACRO
#undef DEFINED_NAME_MACRO
#undef AUTOGENERATE_NAME
#endif

#endif	//HEADER_GUARD

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#endif	//	!ENUMS_ONLY

