/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "SubstanceAirEdNames.h"

// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_SUBSTANCEAIRED_BROWSER_ENUMS
#define INCLUDED_SUBSTANCEAIRED_BROWSER_ENUMS 1


#endif // !INCLUDED_SUBSTANCEAIRED_BROWSER_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_SUBSTANCEAIRED_BROWSER_CLASSES
#define INCLUDED_SUBSTANCEAIRED_BROWSER_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

class UGenericBrowserType_SubstanceAirGraphInstance : public UGenericBrowserType
{
public:
    //## BEGIN PROPS GenericBrowserType_SubstanceAirGraphInstance
    //## END PROPS GenericBrowserType_SubstanceAirGraphInstance

    DECLARE_CLASS(UGenericBrowserType_SubstanceAirGraphInstance,UGenericBrowserType,0,SubstanceAirEd)
	virtual void Init();
	virtual UBOOL NotifyPreDeleteObject(UObject* ObjectToDelete);
	virtual void QuerySupportedCommands(class USelection* InObjects, TArray< FObjectSupportedCommandType >& OutCommands) const;
	virtual void InvokeCustomCommand(INT InCommand, TArray<UObject*>& InObjects);
	UBOOL ShowObjectEditor(UObject* InObject);
};

class UGenericBrowserType_SubstanceAirImageInput : public UGenericBrowserType
{
public:
    //## BEGIN PROPS GenericBrowserType_SubstanceAirImageInput
    //## END PROPS GenericBrowserType_SubstanceAirImageInput

    DECLARE_CLASS(UGenericBrowserType_SubstanceAirImageInput,UGenericBrowserType,0,SubstanceAirEd)
	virtual void Init();
	virtual void QuerySupportedCommands( class USelection* InObjects, TArray< FObjectSupportedCommandType >& OutCommands ) const;
	virtual void InvokeCustomCommand( INT InCommand, TArray<UObject*>& InObjects );
	virtual UBOOL ShowObjectProperties(UObject* InObject);
};

class UGenericBrowserType_SubstanceAirInstanceFactory : public UGenericBrowserType
{
public:
    //## BEGIN PROPS GenericBrowserType_SubstanceAirInstanceFactory
    //## END PROPS GenericBrowserType_SubstanceAirInstanceFactory

    DECLARE_CLASS(UGenericBrowserType_SubstanceAirInstanceFactory,UGenericBrowserType,0,SubstanceAirEd)
	virtual void Init();
	virtual UBOOL NotifyPreDeleteObject(UObject* ObjectToDelete);
	virtual void QuerySupportedCommands(class USelection* InObjects, TArray< FObjectSupportedCommandType >& OutCommands) const;
	virtual void InvokeCustomCommand(INT InCommand, TArray<UObject*>& InObjects);
	
	virtual INT QueryDefaultCommand( TArray<UObject*>& InObjects ) const;
	virtual UBOOL ShowObjectProperties( UObject* InObject );
};

class UGenericBrowserType_SubstanceAirTexture2D : public UGenericBrowserType_Texture
{
public:
    //## BEGIN PROPS GenericBrowserType_SubstanceAirTexture2D
    //## END PROPS GenericBrowserType_SubstanceAirTexture2D

    DECLARE_CLASS(UGenericBrowserType_SubstanceAirTexture2D,UGenericBrowserType_Texture,0,SubstanceAirEd)
	virtual void Init();
	virtual void QuerySupportedCommands( class USelection* InObjects, TArray< FObjectSupportedCommandType >& OutCommands ) const;
	virtual void InvokeCustomCommand( INT InCommand, TArray<UObject*>& InObjects );
	virtual UBOOL NotifyPreDeleteObject(UObject* ObjectToDelete);
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_SUBSTANCEAIRED_BROWSER_CLASSES
#endif // !NAMES_ONLY


#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef SUBSTANCEAIRED_BROWSER_NATIVE_DEFS
#define SUBSTANCEAIRED_BROWSER_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_SUBSTANCEAIRED_BROWSER \
	UGenericBrowserType_SubstanceAirGraphInstance::StaticClass(); \
	UGenericBrowserType_SubstanceAirImageInput::StaticClass(); \
	UGenericBrowserType_SubstanceAirInstanceFactory::StaticClass(); \
	UGenericBrowserType_SubstanceAirTexture2D::StaticClass(); \

#endif // SUBSTANCEAIRED_BROWSER_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UGenericBrowserType_SubstanceAirGraphInstance)
VERIFY_CLASS_SIZE_NODIE(UGenericBrowserType_SubstanceAirImageInput)
VERIFY_CLASS_SIZE_NODIE(UGenericBrowserType_SubstanceAirInstanceFactory)
VERIFY_CLASS_SIZE_NODIE(UGenericBrowserType_SubstanceAirTexture2D)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
