
/** Autogenerated file. Do not edit */

#if !PS3
     #pragma warning(disable : 4100 4206 4244 4996 4127 4121)
#endif

#include "UnBuild.h"

#if WITH_GAMESPY
     #include "../../External/GameSpy/sc/sciWebServices.c"
#endif


