/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "EngineNames.h"

// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_ENGINE_FOGVOLUME_ENUMS
#define INCLUDED_ENGINE_FOGVOLUME_ENUMS 1


#endif // !INCLUDED_ENGINE_FOGVOLUME_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_ENGINE_FOGVOLUME_CLASSES
#define INCLUDED_ENGINE_FOGVOLUME_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

class AFogVolumeDensityInfo : public AInfo
{
public:
    //## BEGIN PROPS FogVolumeDensityInfo
    class UFogVolumeDensityComponent* DensityComponent;
    class UStaticMeshComponent* AutomaticMeshComponent;
    BITFIELD bEnabled:1;
    SCRIPT_ALIGN;
    //## END PROPS FogVolumeDensityInfo

    DECLARE_ABSTRACT_CLASS(AFogVolumeDensityInfo,AInfo,0,Engine)
public:
	virtual void Serialize(FArchive& Ar);
	virtual void PostLoad();
	virtual void PostEditImport();
	virtual void SetupDefaultFogVolume();
};

class AFogVolumeConeDensityInfo : public AFogVolumeDensityInfo
{
public:
    //## BEGIN PROPS FogVolumeConeDensityInfo
    //## END PROPS FogVolumeConeDensityInfo

    DECLARE_ABSTRACT_CLASS(AFogVolumeConeDensityInfo,AFogVolumeDensityInfo,0,Engine)
#if WITH_EDITOR
	// AActor interface.
	virtual void EditorApplyScale(const FVector& DeltaScale, const FMatrix& ScaleMatrix, const FVector* PivotLocation, UBOOL bAltDown, UBOOL bShiftDown, UBOOL bCtrlDown);
#endif
};

class AFogVolumeConstantDensityInfo : public AFogVolumeDensityInfo
{
public:
    //## BEGIN PROPS FogVolumeConstantDensityInfo
    //## END PROPS FogVolumeConstantDensityInfo

    DECLARE_CLASS(AFogVolumeConstantDensityInfo,AFogVolumeDensityInfo,0,Engine)
    NO_DEFAULT_CONSTRUCTOR(AFogVolumeConstantDensityInfo)
};

class AFogVolumeLinearHalfspaceDensityInfo : public AFogVolumeDensityInfo
{
public:
    //## BEGIN PROPS FogVolumeLinearHalfspaceDensityInfo
    //## END PROPS FogVolumeLinearHalfspaceDensityInfo

    DECLARE_CLASS(AFogVolumeLinearHalfspaceDensityInfo,AFogVolumeDensityInfo,0,Engine)
    NO_DEFAULT_CONSTRUCTOR(AFogVolumeLinearHalfspaceDensityInfo)
};

class AFogVolumeSphericalDensityInfo : public AFogVolumeDensityInfo
{
public:
    //## BEGIN PROPS FogVolumeSphericalDensityInfo
    //## END PROPS FogVolumeSphericalDensityInfo

    DECLARE_CLASS(AFogVolumeSphericalDensityInfo,AFogVolumeDensityInfo,0,Engine)
    NO_DEFAULT_CONSTRUCTOR(AFogVolumeSphericalDensityInfo)
};

class UExponentialHeightFogComponent : public UActorComponent
{
public:
    //## BEGIN PROPS ExponentialHeightFogComponent
    BITFIELD bEnabled:1;
    FLOAT FogHeight;
    FLOAT FogDensity;
    FLOAT FogHeightFalloff;
    FLOAT FogMaxOpacity;
    FLOAT StartDistance;
    FLOAT LightTerminatorAngle;
    FLOAT OppositeLightBrightness;
    FColor OppositeLightColor;
    FLOAT LightInscatteringBrightness;
    FColor LightInscatteringColor;
    //## END PROPS ExponentialHeightFogComponent

    void SetEnabled(UBOOL bSetEnabled);
    DECLARE_FUNCTION(execSetEnabled)
    {
        P_GET_UBOOL(bSetEnabled);
        P_FINISH;
        this->SetEnabled(bSetEnabled);
    }
    DECLARE_CLASS(UExponentialHeightFogComponent,UActorComponent,0,Engine)
protected:
	// ActorComponent interface.
	virtual void SetParentToWorld(const FMatrix& ParentToWorld);
	virtual void Attach();
	virtual void UpdateTransform();
	virtual void Detach( UBOOL bWillReattach = FALSE );
public:
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent);
};

class UFogVolumeDensityComponent : public UActorComponent
{
public:
    //## BEGIN PROPS FogVolumeDensityComponent
    class UMaterialInterface* FogMaterial;
    class UMaterialInterface* DefaultFogVolumeMaterial;
    BITFIELD bEnabled:1;
    BITFIELD bAffectsTranslucency:1;
    BITFIELD bOnlyAffectsTranslucency:1;
    SCRIPT_ALIGN;
    FLinearColor SimpleLightColor;
    FLinearColor ApproxFogLightColor;
    FLOAT StartDistance;
    FLOAT MaxDistance;
    TArrayNoInit<class AActor*> FogVolumeActors;
    //## END PROPS FogVolumeDensityComponent

    void SetEnabled(UBOOL bSetEnabled);
    DECLARE_FUNCTION(execSetEnabled)
    {
        P_GET_UBOOL(bSetEnabled);
        P_FINISH;
        this->SetEnabled(bSetEnabled);
    }
    DECLARE_ABSTRACT_CLASS(UFogVolumeDensityComponent,UActorComponent,0,Engine)
private:
	/** Adds the fog volume components to the scene */
	void AddFogVolumeComponents();

	/** Removes the fog volume components from the scene */
	void RemoveFogVolumeComponents();

	/** 
	 * Sets up FogVolumeActors's mesh components to defaults that are common usage with fog volumes.  
	 * Collision is disabled for the actor, each component gets assigned the default fog volume material,
	 * lighting, shadowing, decal accepting, and occluding are disabled.
	 */
	void SetFogActorDefaults(const INT FogActorIndex);

protected:
	// ActorComponent interface.
	virtual void Attach();
	virtual void UpdateTransform();
	virtual void Detach( UBOOL bWillReattach = FALSE );

	// UObject interface
	virtual void PostEditChangeChainProperty(FPropertyChangedChainEvent& PropertyChangedEvent);

public:
	// FogVolumeDensityComponent interface.
	virtual class FFogVolumeDensitySceneInfo* CreateFogVolumeDensityInfo(const UPrimitiveComponent* MeshComponent) const PURE_VIRTUAL(UFogVolumeDensityComponent::CreateFogVolumeDensityInfo,return NULL;);

	/** Checks for partial fog volume setup that will not render anything. */
#if WITH_EDITOR
	virtual void CheckForErrors();
#endif

	/** Returns FogMaterial if it is valid, otherwise DefaultFogVolumeMaterial */
	UMaterialInterface*	GetMaterial() const;
};

class UFogVolumeConeDensityComponent : public UFogVolumeDensityComponent
{
public:
    //## BEGIN PROPS FogVolumeConeDensityComponent
    FLOAT MaxDensity;
    FVector ConeVertex;
    FLOAT ConeRadius;
    FVector ConeAxis;
    FLOAT ConeMaxAngle;
    class UDrawLightConeComponent* PreviewCone;
    //## END PROPS FogVolumeConeDensityComponent

    DECLARE_CLASS(UFogVolumeConeDensityComponent,UFogVolumeDensityComponent,0,Engine)
protected:
	// ActorComponent interface.
	virtual void SetParentToWorld(const FMatrix& ParentToWorld);
	virtual void Attach();

public:
	// FogVolumeDensityComponent interface.
	virtual class FFogVolumeDensitySceneInfo* CreateFogVolumeDensityInfo(const UPrimitiveComponent* MeshComponent) const;
};

class UFogVolumeConstantDensityComponent : public UFogVolumeDensityComponent
{
public:
    //## BEGIN PROPS FogVolumeConstantDensityComponent
    FLOAT Density;
    //## END PROPS FogVolumeConstantDensityComponent

    DECLARE_CLASS(UFogVolumeConstantDensityComponent,UFogVolumeDensityComponent,0,Engine)
public:
	// FogVolumeDensityComponent interface.
	virtual class FFogVolumeDensitySceneInfo* CreateFogVolumeDensityInfo(const UPrimitiveComponent* MeshComponent) const;
};

class UFogVolumeLinearHalfspaceDensityComponent : public UFogVolumeDensityComponent
{
public:
    //## BEGIN PROPS FogVolumeLinearHalfspaceDensityComponent
    FLOAT PlaneDistanceFactor;
    FPlane HalfspacePlane;
    //## END PROPS FogVolumeLinearHalfspaceDensityComponent

    DECLARE_CLASS(UFogVolumeLinearHalfspaceDensityComponent,UFogVolumeDensityComponent,0,Engine)
protected:
	// ActorComponent interface.
	virtual void SetParentToWorld(const FMatrix& ParentToWorld);

public:
	// FogVolumeDensityComponent interface.
	virtual class FFogVolumeDensitySceneInfo* CreateFogVolumeDensityInfo(const UPrimitiveComponent* MeshComponent) const;
};

class UFogVolumeSphericalDensityComponent : public UFogVolumeDensityComponent
{
public:
    //## BEGIN PROPS FogVolumeSphericalDensityComponent
    FLOAT MaxDensity;
    FVector SphereCenter;
    FLOAT SphereRadius;
    class UDrawLightRadiusComponent* PreviewSphereRadius;
    //## END PROPS FogVolumeSphericalDensityComponent

    DECLARE_CLASS(UFogVolumeSphericalDensityComponent,UFogVolumeDensityComponent,0,Engine)
protected:
	// ActorComponent interface.
	virtual void SetParentToWorld(const FMatrix& ParentToWorld);
	virtual void Attach();

public:
	// FogVolumeDensityComponent interface.
	virtual class FFogVolumeDensitySceneInfo* CreateFogVolumeDensityInfo(const UPrimitiveComponent* MeshComponent) const;
};

class UActorFactoryFogVolumeConstantDensityInfo : public UActorFactory
{
public:
    //## BEGIN PROPS ActorFactoryFogVolumeConstantDensityInfo
    class UMaterialInterface* SelectedMaterial;
    BITFIELD bNothingSelected:1;
    SCRIPT_ALIGN;
    //## END PROPS ActorFactoryFogVolumeConstantDensityInfo

    DECLARE_CLASS(UActorFactoryFogVolumeConstantDensityInfo,UActorFactory,0|CLASS_Config,Engine)
	/**
	 * If the ActorFactory thinks it could create an Actor with the current settings.
	 * Used to determine if we should add to context menu for example.
	 *
	 * @param	OutErrorMsg		Receives localized error string name if returning FALSE.
	 * @param	bFromAssetOnly	If true, the actor factory will check that a valid asset has been assigned from selection.  If the factory always requires an asset to be selected, this param does not matter
	 */
	virtual UBOOL CanCreateActor( FString& OutErrorMsg, UBOOL bFromAssetOnly );
	virtual AActor* CreateActor( const FVector* const Location, const FRotator* const Rotation, const class USeqAct_ActorFactory* const ActorFactoryData );
	virtual void AutoFillFields(class USelection* Selection);
};

class UActorFactoryFogVolumeLinearHalfspaceDensityInfo : public UActorFactoryFogVolumeConstantDensityInfo
{
public:
    //## BEGIN PROPS ActorFactoryFogVolumeLinearHalfspaceDensityInfo
    //## END PROPS ActorFactoryFogVolumeLinearHalfspaceDensityInfo

    DECLARE_CLASS(UActorFactoryFogVolumeLinearHalfspaceDensityInfo,UActorFactoryFogVolumeConstantDensityInfo,0|CLASS_Config,Engine)
    NO_DEFAULT_CONSTRUCTOR(UActorFactoryFogVolumeLinearHalfspaceDensityInfo)
};

class UActorFactoryFogVolumeSphericalDensityInfo : public UActorFactoryFogVolumeConstantDensityInfo
{
public:
    //## BEGIN PROPS ActorFactoryFogVolumeSphericalDensityInfo
    //## END PROPS ActorFactoryFogVolumeSphericalDensityInfo

    DECLARE_CLASS(UActorFactoryFogVolumeSphericalDensityInfo,UActorFactoryFogVolumeConstantDensityInfo,0|CLASS_Config,Engine)
	virtual AActor* CreateActor( const FVector* const Location, const FRotator* const Rotation, const class USeqAct_ActorFactory* const ActorFactoryData );
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_ENGINE_FOGVOLUME_CLASSES
#endif // !NAMES_ONLY

AUTOGENERATE_FUNCTION(UExponentialHeightFogComponent,-1,execSetEnabled);
AUTOGENERATE_FUNCTION(UFogVolumeDensityComponent,-1,execSetEnabled);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef ENGINE_FOGVOLUME_NATIVE_DEFS
#define ENGINE_FOGVOLUME_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_ENGINE_FOGVOLUME \
	AFogVolumeDensityInfo::StaticClass(); \
	AFogVolumeConeDensityInfo::StaticClass(); \
	AFogVolumeConstantDensityInfo::StaticClass(); \
	AFogVolumeLinearHalfspaceDensityInfo::StaticClass(); \
	AFogVolumeSphericalDensityInfo::StaticClass(); \
	UExponentialHeightFogComponent::StaticClass(); \
	GNativeLookupFuncs.Set(FName("ExponentialHeightFogComponent"), GEngineUExponentialHeightFogComponentNatives); \
	UFogVolumeDensityComponent::StaticClass(); \
	GNativeLookupFuncs.Set(FName("FogVolumeDensityComponent"), GEngineUFogVolumeDensityComponentNatives); \
	UFogVolumeConeDensityComponent::StaticClass(); \
	UFogVolumeConstantDensityComponent::StaticClass(); \
	UFogVolumeLinearHalfspaceDensityComponent::StaticClass(); \
	UFogVolumeSphericalDensityComponent::StaticClass(); \
	UActorFactoryFogVolumeConstantDensityInfo::StaticClass(); \
	UActorFactoryFogVolumeLinearHalfspaceDensityInfo::StaticClass(); \
	UActorFactoryFogVolumeSphericalDensityInfo::StaticClass(); \

#endif // ENGINE_FOGVOLUME_NATIVE_DEFS

#ifdef NATIVES_ONLY
FNativeFunctionLookup GEngineUExponentialHeightFogComponentNatives[] = 
{ 
	MAP_NATIVE(UExponentialHeightFogComponent, execSetEnabled)
	{NULL, NULL}
};

FNativeFunctionLookup GEngineUFogVolumeDensityComponentNatives[] = 
{ 
	MAP_NATIVE(UFogVolumeDensityComponent, execSetEnabled)
	{NULL, NULL}
};

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(AFogVolumeDensityInfo,FogVolumeDensityInfo,DensityComponent)
VERIFY_CLASS_OFFSET_NODIE(AFogVolumeDensityInfo,FogVolumeDensityInfo,AutomaticMeshComponent)
VERIFY_CLASS_SIZE_NODIE(AFogVolumeDensityInfo)
VERIFY_CLASS_SIZE_NODIE(AFogVolumeConeDensityInfo)
VERIFY_CLASS_SIZE_NODIE(AFogVolumeConstantDensityInfo)
VERIFY_CLASS_SIZE_NODIE(AFogVolumeLinearHalfspaceDensityInfo)
VERIFY_CLASS_SIZE_NODIE(AFogVolumeSphericalDensityInfo)
VERIFY_CLASS_OFFSET_NODIE(UExponentialHeightFogComponent,ExponentialHeightFogComponent,FogHeight)
VERIFY_CLASS_OFFSET_NODIE(UExponentialHeightFogComponent,ExponentialHeightFogComponent,LightInscatteringColor)
VERIFY_CLASS_SIZE_NODIE(UExponentialHeightFogComponent)
VERIFY_CLASS_OFFSET_NODIE(UFogVolumeDensityComponent,FogVolumeDensityComponent,FogMaterial)
VERIFY_CLASS_OFFSET_NODIE(UFogVolumeDensityComponent,FogVolumeDensityComponent,FogVolumeActors)
VERIFY_CLASS_SIZE_NODIE(UFogVolumeDensityComponent)
VERIFY_CLASS_OFFSET_NODIE(UFogVolumeConeDensityComponent,FogVolumeConeDensityComponent,MaxDensity)
VERIFY_CLASS_OFFSET_NODIE(UFogVolumeConeDensityComponent,FogVolumeConeDensityComponent,PreviewCone)
VERIFY_CLASS_SIZE_NODIE(UFogVolumeConeDensityComponent)
VERIFY_CLASS_OFFSET_NODIE(UFogVolumeConstantDensityComponent,FogVolumeConstantDensityComponent,Density)
VERIFY_CLASS_SIZE_NODIE(UFogVolumeConstantDensityComponent)
VERIFY_CLASS_OFFSET_NODIE(UFogVolumeLinearHalfspaceDensityComponent,FogVolumeLinearHalfspaceDensityComponent,PlaneDistanceFactor)
VERIFY_CLASS_OFFSET_NODIE(UFogVolumeLinearHalfspaceDensityComponent,FogVolumeLinearHalfspaceDensityComponent,HalfspacePlane)
VERIFY_CLASS_SIZE_NODIE(UFogVolumeLinearHalfspaceDensityComponent)
VERIFY_CLASS_OFFSET_NODIE(UFogVolumeSphericalDensityComponent,FogVolumeSphericalDensityComponent,MaxDensity)
VERIFY_CLASS_OFFSET_NODIE(UFogVolumeSphericalDensityComponent,FogVolumeSphericalDensityComponent,PreviewSphereRadius)
VERIFY_CLASS_SIZE_NODIE(UFogVolumeSphericalDensityComponent)
VERIFY_CLASS_OFFSET_NODIE(UActorFactoryFogVolumeConstantDensityInfo,ActorFactoryFogVolumeConstantDensityInfo,SelectedMaterial)
VERIFY_CLASS_SIZE_NODIE(UActorFactoryFogVolumeConstantDensityInfo)
VERIFY_CLASS_SIZE_NODIE(UActorFactoryFogVolumeLinearHalfspaceDensityInfo)
VERIFY_CLASS_SIZE_NODIE(UActorFactoryFogVolumeSphericalDensityInfo)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
