/*===========================================================================
    FName C++ declarations exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if !ENUMS_ONLY
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#if !defined(__ONLINESUBSYSTEMGAMECENTER_NAMES_H__) || defined(NAMES_ONLY)

#ifndef __ONLINESUBSYSTEMGAMECENTER_NAMES_H__
#define __ONLINESUBSYSTEMGAMECENTER_NAMES_H__
#endif

#ifndef AUTOGENERATE_NAME
#define DEFINED_NAME_MACRO
#define AUTOGENERATE_NAME(name) extern FName ONLINESUBSYSTEMGAMECENTER_##name;
#endif


AUTOGENERATE_NAME(OnAddFriendByNameComplete)
AUTOGENERATE_NAME(OnArbitrationRegistrationComplete)
AUTOGENERATE_NAME(OnCancelFindOnlineGamesComplete)
AUTOGENERATE_NAME(OnConnectionStatusChange)
AUTOGENERATE_NAME(OnControllerChange)
AUTOGENERATE_NAME(OnCreateOnlineGameComplete)
AUTOGENERATE_NAME(OnDestroyOnlineGameComplete)
AUTOGENERATE_NAME(OnDeviceSelectionComplete)
AUTOGENERATE_NAME(OnEndOnlineGameComplete)
AUTOGENERATE_NAME(OnExternalUIChange)
AUTOGENERATE_NAME(OnFindOnlineGamesComplete)
AUTOGENERATE_NAME(OnFlushOnlineStatsComplete)
AUTOGENERATE_NAME(OnFriendInviteReceived)
AUTOGENERATE_NAME(OnFriendMessageReceived)
AUTOGENERATE_NAME(OnFriendsChange)
AUTOGENERATE_NAME(OnGameInviteAccepted)
AUTOGENERATE_NAME(OnJoinFriendGameComplete)
AUTOGENERATE_NAME(OnJoinMigratedOnlineGameComplete)
AUTOGENERATE_NAME(OnJoinOnlineGameComplete)
AUTOGENERATE_NAME(OnKeyboardInputComplete)
AUTOGENERATE_NAME(OnLinkStatusChange)
AUTOGENERATE_NAME(OnLoginCancelled)
AUTOGENERATE_NAME(OnLoginChange)
AUTOGENERATE_NAME(OnLoginFailed)
AUTOGENERATE_NAME(OnLoginStatusChange)
AUTOGENERATE_NAME(OnLogoutCompleted)
AUTOGENERATE_NAME(OnMigrateOnlineGameComplete)
AUTOGENERATE_NAME(OnMutingChange)
AUTOGENERATE_NAME(OnPlayerTalkingStateChange)
AUTOGENERATE_NAME(OnProfileDataChanged)
AUTOGENERATE_NAME(OnQosStatusChanged)
AUTOGENERATE_NAME(OnReadAchievementsComplete)
AUTOGENERATE_NAME(OnReadCrossTitleProfileSettingsComplete)
AUTOGENERATE_NAME(OnReadFriendsComplete)
AUTOGENERATE_NAME(OnReadOnlineStatsComplete)
AUTOGENERATE_NAME(OnReadPlayerStorageComplete)
AUTOGENERATE_NAME(OnReadPlayerStorageForNetIdComplete)
AUTOGENERATE_NAME(OnReadProfileSettingsComplete)
AUTOGENERATE_NAME(OnReadTitleFileComplete)
AUTOGENERATE_NAME(OnRecalculateSkillRatingComplete)
AUTOGENERATE_NAME(OnReceivedGameInvite)
AUTOGENERATE_NAME(OnRecognitionComplete)
AUTOGENERATE_NAME(OnRegisterHostStatGuidComplete)
AUTOGENERATE_NAME(OnRegisterPlayerComplete)
AUTOGENERATE_NAME(OnShowOnlineStatsUIComplete)
AUTOGENERATE_NAME(OnStartOnlineGameComplete)
AUTOGENERATE_NAME(OnStorageDeviceChange)
AUTOGENERATE_NAME(OnUnlockAchievementComplete)
AUTOGENERATE_NAME(OnUnregisterPlayerComplete)
AUTOGENERATE_NAME(OnUpdateOnlineGameComplete)
AUTOGENERATE_NAME(OnWritePlayerStorageComplete)
AUTOGENERATE_NAME(OnWriteProfileSettingsComplete)

#ifdef DEFINED_NAME_MACRO
#undef DEFINED_NAME_MACRO
#undef AUTOGENERATE_NAME
#endif

#endif	//HEADER_GUARD

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#endif	//	!ENUMS_ONLY

