<?xml version="1.0" encoding="utf-8"?><Database Name="Builder" Class="BuildersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=db-09;Initial Catalog=Builder;Integrated Security=True" SettingsObjectName="Controller.Properties.Settings" SettingsPropertyName="BuilderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Builders" Member="Builders">
    <Type Name="Builder">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Machine" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Deployed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CurrentTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CurrentStatus" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="DirectXSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="AndroidSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="iPhoneSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="MacSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="NGPSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="PS3SDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="WiiUSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Xbox360SDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="FlashSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="CPUString" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="ProcessorCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Memory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DriveCSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DriveCFree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DriveDSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DriveDFree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>