<?xml version="1.0" encoding="utf-8"?><Database Name="Builder" Class="Changelist2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=db-09;Initial Catalog=Builder;Integrated Security=True" SettingsObjectName="Controller.Properties.Settings" SettingsPropertyName="BuilderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Changelists2" Member="Changelists2s">
    <Type Name="Changelists2">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchConfigID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Changelist" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuildStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Submitter" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Changelists2_CISJobStateAlt" Member="CISJobStateAlts" ThisKey="ID" OtherKey="ChangelistID" Type="CISJobStateAlt" />
      <Association Name="BranchConfigAlt_Changelists2" Member="BranchConfigAlt" ThisKey="BranchConfigID" OtherKey="ID" Type="BranchConfigAlt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CISJobStates" Member="CISJobStateAlts">
    <Type Name="CISJobStateAlt">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChangelistID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CISTaskID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JobState" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Error" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Changelists2_CISJobStateAlt" Member="Changelists2" ThisKey="ChangelistID" OtherKey="ID" Type="Changelists2" IsForeignKey="true" />
      <Association Name="CISTask_CISJobStateAlt" Member="CISTaskAlt" ThisKey="CISTaskID" OtherKey="ID" Type="CISTaskAlt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BranchConfig" Member="BranchConfigAlts">
    <Type Name="BranchConfigAlt">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Branch" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Server" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="P4User" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="P4Password" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="P4SyncUser" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="P4SyncPassword" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="P4ClientSpec" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="BranchAdmin" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="DirectXVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="AndroidSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="iPhoneSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="MacSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="NGPSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="PS3SDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="WiiUSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Xbox360SDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="FlashSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="PFXSubjectName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="IPhone_DeveloperSigningIdentity" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="IPhone_DistributionSigningIdentity" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="HeadChangelist" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastFullyKnown" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastGoodOverall" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastFailOverall" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastAttemptedOverall" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BranchConfigAlt_Changelists2" Member="Changelists2s" ThisKey="ID" OtherKey="BranchConfigID" Type="Changelists2" />
      <Association Name="BranchConfigAlt_BranchConfigAlt" Member="BranchConfigAlt1" ThisKey="ID" OtherKey="ID" Type="BranchConfigAlt" Cardinality="One" />
      <Association Name="BranchConfigAlt_Job" Member="JobAlts" ThisKey="ID" OtherKey="BranchConfigID" Type="JobAlt" />
      <Association Name="BranchConfigAlt_BranchConfigAlt" Member="BranchConfig1" ThisKey="ID" OtherKey="ID" Type="BranchConfigAlt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Jobs" Member="JobAlts">
    <Type Name="JobAlt">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Command" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Platform" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="Game" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Config" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ScriptConfig" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Define" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Parameter" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="Remote" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BranchConfigID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CISTaskID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CISJobStateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(96)" CanBeNull="true" />
      <Column Name="Machine" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="BuildLogID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrimaryBuild" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Complete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Succeeded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Optional" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Killing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Suppressed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SpawnTime" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="BranchConfigAlt_Job" Member="BranchConfigAlt" ThisKey="BranchConfigID" OtherKey="ID" Type="BranchConfigAlt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CISTasks" Member="CISTaskAlts">
    <Type Name="CISTaskAlt">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="BranchConfigID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mask" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastAttempted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastGood" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastFail" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GameSpecific" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PlatformSpecific" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Remote" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CompileAllowed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Folders" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DependentPlatforms" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AlternateFolders" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="CISTask_CISJobStateAlt" Member="CISJobStateAlts" ThisKey="ID" OtherKey="CISTaskID" Type="CISJobStateAlt" />
    </Type>
  </Table>
</Database>