<?xml version="1.0" encoding="utf-8"?><Database Name="Builder" Class="BranchConfigsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=db-09;Initial Catalog=Builder;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BuilderConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BranchConfig" Member="BranchConfigs">
    <Type Name="BranchConfig">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Branch" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Server" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="P4User" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="P4Password" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="P4SyncUser" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="P4SyncPassword" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="P4ClientSpec" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="BranchAdmin" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="DirectXVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="AndroidSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="iPhoneSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="MacSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="NGPSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="PS3SDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="WiiUSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Xbox360SDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="FlashSDKVersion" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="PFXSubjectName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="IPhone_DeveloperSigningIdentity" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="IPhone_DistributionSigningIdentity" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="HeadChangelist" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastFullyKnown" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastGoodOverall" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastFailOverall" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastAttemptedOverall" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BranchConfig_BranchConfig" Member="BranchConfig2" ThisKey="ID" OtherKey="ID" Type="BranchConfig" Cardinality="One" />
      <Association Name="BranchConfig_BranchConfig" Member="BranchConfig1" ThisKey="ID" OtherKey="ID" Type="BranchConfig" IsForeignKey="true" />
    </Type>
  </Table>
</Database>