/*=============================================================================
	ShaderComplexityAccumulatePixelShader.usf: Outputs complexity
	Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#include "Common.usf"

float NormalizedComplexity;

void Main(out float4 OutColor : COLOR0)
{
	//use the maximum range allowed for scene color
	OutColor = RETURN_COLOR(float4(NormalizedComplexity.xxx, 0));
}
