/*=============================================================================
 Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#ifndef __D3DMESHUTILS_H__
#define __D3DMESHUTILS_H__

#if _WINDOWS && !UE3_LEAN_AND_MEAN

/**
 * This utility class builds on D3DX functionality. Used for editor helpers.
 */
namespace D3D9MeshUtilities
{
	/**
	 * Generates a unique UV layout for a static mesh
	 * @param StaticMesh - The input/output mesh
	 * @param LODIndex - The LOD level
	 * @param TexCoordIndex - Index of the uv channel to overwrite or create
	 * @param bKeepExistingCoordinates - True to preserve the existing charts when packing
	 * @param MinChartSpacingPercent - Minimum distance between two packed charts (0.0-100.0)
	 * @param BorderSpacingPercent - Spacing between UV border and charts (0.0-100.0)
	 * @param bUseMaxStretch - True if "MaxDesiredStretch" should be used; otherwise "MaxCharts" is used
	 * @param InFalseEdgeIndices - Optional list of raw face edge indices to be ignored when creating UV seams
	 * @param MaxCharts - In: Max number of charts to allow; Out:Number of charts generated by the uv unwrap algorithm.
	 * @param MaxDesiredStretch - The amount of stretching allowed. 0 means no stretching is allowed, 1 means any amount of stretching can be used. 
	 * @return TRUE if successful
	 */
	UBOOL GenerateUVs(
		UStaticMesh* StaticMesh,
		UINT LODIndex,
		UINT TexCoordIndex,
		UBOOL bKeepExistingCoordinates,
		FLOAT MinChartSpacingPercent,
		FLOAT BorderSpacingPercent,
		UBOOL bUseMaxStretch,
		const TArray< INT >* InFalseEdgeIndices,
		UINT& MaxCharts,
		FLOAT& MaxDesiredStretch
		);
	/**
	* For quick generating lightmap uvs.
	* It copies charts from 0 uv channel and layouts them without making new charts (keeps edge splits). Additionally separates folded triangles automatically
	* Use when DXD generates ugly cuts and degenerates charts 
	* @param StaticMesh - The input/output mesh
	* @param LODIndex - The LOD level
	* @param TexCoordIndex - Index of the uv channel to overwrite or create
	* @return TRUE if successful
	*/
	UBOOL LayoutUVs(
		UStaticMesh* StaticMesh,
		UINT LODIndex,
		UINT TexCoordIndex
		);
}

#endif

#endif
