/*=============================================================================
	StatusBars : All the status bars the editor uses

	Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

enum EStatusBar
{
	SB_Standard,
	SB_Max,
};

///////////////////////////////////////////////////////////////////////////////

/**
 * The standard editor status bar.  Displayed during normal editing.
 */
class WxStatusBarStandard : public WxStatusBar
{
public:
	WxStatusBarStandard();

	virtual void SetUp();
	virtual void UpdateUI();

	/** Update the position and size of the status bar */
	virtual void RefreshPositionAndSize();

	/** Adds the specified string to the combo box list if it's not already there. */
	void AddToExecCombo( const FString& InExec );


	/**
	 * Sets the mouse worldspace position text field to the text passed in.
	 *
	 * @param StatusText	 String to use as the new text for the worldspace position field.
	 */
	virtual void SetMouseWorldspacePositionText( const TCHAR* StatusText );

protected:

	wxComboBox *ExecCombo;
	wxBitmap DragGridB, RotationGridB;
	wxCheckBox *DragGridCB, *RotationGridCB, *ScaleGridCB, *AutoSaveCB;
	wxStaticBitmap *DragGridSB, *RotationGridSB;
	wxStaticText *DragGridST, *RotationGridST, *ScaleGridST;
	wxStaticText *ActorNameST;
	WxMenuButton *DragGridMB, *RotationGridMB, *ScaleGridMB, *AutoSaveMB;

	class WxScaleTextCtrl *DrawScaleTextCtrl;
	class WxScaleTextCtrl *DrawScaleXTextCtrl;
	class WxScaleTextCtrl *DrawScaleYTextCtrl;
	class WxScaleTextCtrl *DrawScaleZTextCtrl;

	INT DragTextWidth, RotationTextWidth, ScaleTextWidth;

	/** Bitmaps that indicate the current status of autosave. */
	WxBitmap AutosaveEnabled, AutosaveDisabled, AutosaveSoon;
	wxStaticBitmap *AutoSaveSB;

	/** Bitmaps that indicate the current status of lighting, source control, and paths */
	WxBitmap SCCEnabledB, SCCDisabledB, SCCConnectionProblemB, LightingDirtyB, LightingNotDirtyB, PathsDirtyB, PathsNotDirtyB; 
	WxBitmapStateButton *SCCStatusBCB, *LightingStatusBCB, *PathsStatusBCB;

	/** Bitmaps indicating that modified packages need to be checked out */
	WxBitmap PackagesNeedCheckout, PackagesDontNeedCheckout;
	WxBitmapStateButton* PackagesNeedCheckoutBCB;

private:

	/** Enumeration representing the status of the source control icon */
	enum ESCCStatus
	{
		SCCS_Enabled,
		SCCS_Disabled,
		SCCS_ConnectionProblems
	};

	/** Enumeration representing the status of the lighting icon */
	enum ELightingStatus
	{
		LS_Dirty,
		LS_NotDirty
	};

	/** Enumeration representing the status of the paths icon */
	enum EPathsStatus
	{
		PS_Dirty,
		PS_NotDirty,
	};

	enum EPackageCheckoutStatus
	{
		PCS_CheckoutNeeded,
		PCS_CheckoutNotNeeded,
	};

	/**
	 * Overload for the default SetStatusText function.  This overload maps
	 * any text set to field 0, to field 1 because the command combo box takes up
	 * field 0.
	 */
	virtual void SetStatusText( const wxString& InText, INT InFieldIdx );

	void OnSize( wxSizeEvent& InEvent );
	void OnDragGridToggleClick( wxCommandEvent& InEvent );
	void OnRotationGridToggleClick( wxCommandEvent& InEvent );
	void OnScaleGridToggleClick( wxCommandEvent& InEvent );
	void OnAutosaveToggleClick( wxCommandEvent& InEvent );
	void OnDrawScale( wxCommandEvent& In );
	void OnDrawScaleX( wxCommandEvent& In );
	void OnDrawScaleY( wxCommandEvent& In );
	void OnDrawScaleZ( wxCommandEvent& In );
	void OnExecComboEnter( wxCommandEvent& In );
	void OnExecComboSelChange( wxCommandEvent& In );

	/**
	 * Called by wxWidgets when the user clicks the SCC status button
	 *
	 * @param	In	Event automatically generated by wxWidgets when the user clicks the SCC status button
	 */
	void OnClickSCCStatusButton( wxCommandEvent& In );

	/**
	 * Called by wxWidgets when the user clicks the lighting status button
	 *
	 * @param	In	Event automatically generated by wxWidgets when the user clicks the lighting status button
	 */
	void OnClickLightingStatusButton( wxCommandEvent& In );
	
	/**
	 * Called by wxWidgets when the user clicks the paths status button
	 *
	 * @param	In	Event automatically generated by wxWidgets when the user clicks the paths status button
	 */
	void OnClickPathsStatusButton( wxCommandEvent& In );

	/**
	 * Called by wxWidgets when the user clicks the package checkout status button
	 *
	 * @param 	In	Event automatically generated by wxWidgets when the user clicks the package checkout status button
	 */
	void OnClickPackageCheckoutStatusButton( wxCommandEvent& In );

	/**
	 * Called automatically by wxWidgets to update the UI
	 *
	 * @param	Event	Event automatically generated by wxWidgets to update the UI
	 */
	void OnUpdateUI(wxUpdateUIEvent &Event );

	void UpdateStatusWidths();

	DECLARE_EVENT_TABLE()
};

