/**
 * Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
 */

/*-----------------------------------------------------------------------------
	Standard OpenAL functions.
-----------------------------------------------------------------------------*/

AL_EXT(_AL,AL)

AL_PROC(_AL,AL,void,alEnable,( ALenum capability ))
AL_PROC(_AL,AL,void,alDisable,( ALenum capability )) 
AL_PROC(_AL,AL,ALboolean,alIsEnabled,( ALenum capability )) 
AL_PROC(_AL,AL,const ALchar*,alGetString,( ALenum param ))
AL_PROC(_AL,AL,void,alGetBooleanv,( ALenum param, ALboolean* data ))
AL_PROC(_AL,AL,void,alGetIntegerv,( ALenum param, ALint* data ))
AL_PROC(_AL,AL,void,alGetFloatv,( ALenum param, ALfloat* data ))
AL_PROC(_AL,AL,void,alGetDoublev,( ALenum param, ALdouble* data ))
AL_PROC(_AL,AL,ALboolean,alGetBoolean,( ALenum param ))
AL_PROC(_AL,AL,ALint,alGetInteger,( ALenum param ))
AL_PROC(_AL,AL,ALfloat,alGetFloat,( ALenum param ))
AL_PROC(_AL,AL,ALdouble,alGetDouble,( ALenum param ))
AL_PROC(_AL,AL,ALenum,alGetError,( void ))
AL_PROC(_AL,AL,ALboolean,alIsExtensionPresent,( const ALchar* extname ))
AL_PROC(_AL,AL,void*,alGetProcAddress,( const ALchar* fname ))
AL_PROC(_AL,AL,ALenum,alGetEnumValue,( const ALchar* ename ))
AL_PROC(_AL,AL,void,alListenerf,( ALenum param, ALfloat value ))
AL_PROC(_AL,AL,void,alListener3f,( ALenum param, ALfloat value1, ALfloat value2, ALfloat value3 ))
AL_PROC(_AL,AL,void,alListenerfv,( ALenum param, const ALfloat* values )) 
AL_PROC(_AL,AL,void,alListeneri,( ALenum param, ALint value ))
AL_PROC(_AL,AL,void,alListener3i,( ALenum param, ALint value1, ALint value2, ALint value3 ))
AL_PROC(_AL,AL,void,alListeneriv,( ALenum param, const ALint* values ))
AL_PROC(_AL,AL,void,alGetListenerf,( ALenum param, ALfloat* value ))
AL_PROC(_AL,AL,void,alGetListener3f,( ALenum param, ALfloat *value1, ALfloat *value2, ALfloat *value3 ))
AL_PROC(_AL,AL,void,alGetListenerfv,( ALenum param, ALfloat* values ))
AL_PROC(_AL,AL,void,alGetListeneri,( ALenum param, ALint* value ))
AL_PROC(_AL,AL,void,alGetListener3i,( ALenum param, ALint *value1, ALint *value2, ALint *value3 ))
AL_PROC(_AL,AL,void,alGetListeneriv,( ALenum param, ALint* values ))
AL_PROC(_AL,AL,void,alGenSources,( ALsizei n, ALuint* sources )) 
AL_PROC(_AL,AL,void,alDeleteSources,( ALsizei n, const ALuint* sources ))
AL_PROC(_AL,AL,ALboolean,alIsSource,( ALuint sid )) 
AL_PROC(_AL,AL,void,alSourcef,( ALuint sid, ALenum param, ALfloat value )) 
AL_PROC(_AL,AL,void,alSource3f,( ALuint sid, ALenum param, ALfloat value1, ALfloat value2, ALfloat value3 ))
AL_PROC(_AL,AL,void,alSourcefv,( ALuint sid, ALenum param, const ALfloat* values )) 
AL_PROC(_AL,AL,void,alSourcei,( ALuint sid, ALenum param, ALint value )) 
AL_PROC(_AL,AL,void,alSource3i,( ALuint sid, ALenum param, ALint value1, ALint value2, ALint value3 ))
AL_PROC(_AL,AL,void,alSourceiv,( ALuint sid, ALenum param, const ALint* values ))
AL_PROC(_AL,AL,void,alGetSourcef,( ALuint sid, ALenum param, ALfloat* value ))
AL_PROC(_AL,AL,void,alGetSource3f,( ALuint sid, ALenum param, ALfloat* value1, ALfloat* value2, ALfloat* value3))
AL_PROC(_AL,AL,void,alGetSourcefv,( ALuint sid, ALenum param, ALfloat* values ))
AL_PROC(_AL,AL,void,alGetSourcei,( ALuint sid,  ALenum param, ALint* value ))
AL_PROC(_AL,AL,void,alGetSource3i,( ALuint sid, ALenum param, ALint* value1, ALint* value2, ALint* value3))
AL_PROC(_AL,AL,void,alGetSourceiv,( ALuint sid,  ALenum param, ALint* values ))
AL_PROC(_AL,AL,void,alSourcePlayv,( ALsizei ns, const ALuint *sids ))
AL_PROC(_AL,AL,void,alSourceStopv,( ALsizei ns, const ALuint *sids ))
AL_PROC(_AL,AL,void,alSourceRewindv,( ALsizei ns, const ALuint *sids ))
AL_PROC(_AL,AL,void,alSourcePausev,( ALsizei ns, const ALuint *sids ))
AL_PROC(_AL,AL,void,alSourcePlay,( ALuint sid ))
AL_PROC(_AL,AL,void,alSourceStop,( ALuint sid ))
AL_PROC(_AL,AL,void,alSourceRewind,( ALuint sid ))
AL_PROC(_AL,AL,void,alSourcePause,( ALuint sid ))
AL_PROC(_AL,AL,void,alSourceQueueBuffers,( ALuint sid, ALsizei numEntries, const ALuint *bids ))
AL_PROC(_AL,AL,void,alSourceUnqueueBuffers,( ALuint sid, ALsizei numEntries, ALuint *bids ))
AL_PROC(_AL,AL,void,alGenBuffers,( ALsizei n, ALuint* buffers ))
AL_PROC(_AL,AL,void,alDeleteBuffers,( ALsizei n, const ALuint* buffers ))
AL_PROC(_AL,AL,ALboolean,alIsBuffer,( ALuint bid ))
AL_PROC(_AL,AL,void,alBufferData,( ALuint bid, ALenum format, const ALvoid* data, ALsizei size, ALsizei freq ))
AL_PROC(_AL,AL,void,alBufferf,( ALuint bid, ALenum param, ALfloat value ))
AL_PROC(_AL,AL,void,alBufferi,( ALuint bid, ALenum param, ALint value ))
AL_PROC(_AL,AL,void,alGetBufferf,( ALuint bid, ALenum param, ALfloat* value ))
AL_PROC(_AL,AL,void,alGetBufferi,( ALuint bid, ALenum param, ALint* value ))
AL_PROC(_AL,AL,void,alDopplerFactor,( ALfloat value ))
AL_PROC(_AL,AL,void,alDopplerVelocity,( ALfloat value ))
AL_PROC(_AL,AL,void,alSpeedOfSound,( ALfloat value ))
AL_PROC(_AL,AL,void,alDistanceModel,( ALenum distanceModel ))

AL_PROC(_AL,AL,ALCcontext*,alcCreateContext,( ALCdevice *device, const ALCint* attrlist ))
AL_PROC(_AL,AL,ALCboolean,alcMakeContextCurrent,( ALCcontext *context ))
AL_PROC(_AL,AL,void,alcProcessContext,( ALCcontext *context ))
AL_PROC(_AL,AL,void,alcSuspendContext,( ALCcontext *context ))
AL_PROC(_AL,AL,void,alcDestroyContext,( ALCcontext *context ))
AL_PROC(_AL,AL,ALCcontext*,alcGetCurrentContext,( ALCvoid ))
AL_PROC(_AL,AL,ALCdevice*,alcGetContextsDevice,( ALCcontext *context ))
AL_PROC(_AL,AL,ALCdevice*,alcOpenDevice,( const ALCchar *devicename ))
AL_PROC(_AL,AL,ALCboolean,alcCloseDevice,( ALCdevice *device ))
AL_PROC(_AL,AL,ALCenum,alcGetError,( ALCdevice *device ))
AL_PROC(_AL,AL,ALCboolean,alcIsExtensionPresent,( ALCdevice *device, const ALCchar *extname ))
AL_PROC(_AL,AL,void*,alcGetProcAddress,( ALCdevice *device, const ALCchar *funcname ))
AL_PROC(_AL,AL,ALCenum,alcGetEnumValue,( ALCdevice *device, const ALCchar *enumname ))
AL_PROC(_AL,AL,const ALCchar*,alcGetString,( ALCdevice *device, ALCenum param ))
AL_PROC(_AL,AL,void,alcGetIntegerv,( ALCdevice *device, ALCenum param, ALCsizei size, ALCint *data ))
AL_PROC(_AL,AL,ALCdevice*,alcCaptureOpenDevice,( const ALCchar *devicename, ALCuint frequency, ALCenum format, ALCsizei buffersize ))
AL_PROC(_AL,AL,ALCboolean,alcCaptureCloseDevice,( ALCdevice *device ))
AL_PROC(_AL,AL,void,alcCaptureStart,( ALCdevice *device ))
AL_PROC(_AL,AL,void,alcCaptureStop,( ALCdevice *device ))
AL_PROC(_AL,AL,void,alcCaptureSamples,( ALCdevice *device, ALCvoid *buffer, ALCsizei samples ))

/*-----------------------------------------------------------------------------
	OpenAL extensions.
-----------------------------------------------------------------------------*/

#if _WINDOWS
AL_EXT(_EAX4,EAX4.0)
AL_PROC(_EAX4,EAX4.0,ALenum,EAXGet,( const GUID *object, ALuint property, ALuint sid, ALvoid *value, ALuint size ))
AL_PROC(_EAX4,EAX4.0,ALenum,EAXSet,( const GUID *object, ALuint property, ALuint sid, ALvoid *value, ALuint size ))
#endif

AL_EXT(_EAXRAM,EAX-RAM)
AL_PROC(_EAXRAM,EAX-RAM,ALenum,EAXGetBufferMode,( ALuint buffer,ALint *value ))
AL_PROC(_EAXRAM,EAX-RAM,ALboolean,EAXSetBufferMode,( ALsizei n,ALuint *buffers,ALint value ))

AL_EXT(_EFX,ALC_EXT_EFX)
AL_PROC(_EFX,ALC_EXT_EFX,void,alGenEffects,( ALsizei n, ALuint *effects ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alDeleteEffects,( ALsizei n, ALuint *effects ))
AL_PROC(_EFX,ALC_EXT_EFX,ALboolean,alIsEffect,( ALuint effect ))

AL_PROC(_EFX,ALC_EXT_EFX,void,alEffectf,( ALuint effect, ALenum param, ALfloat value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alEffecti,( ALuint effect, ALenum param, ALint value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alEffectfv,( ALuint effect, ALenum param, ALfloat *values ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alEffectiv,( ALuint effect, ALenum param, ALint *values ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetEffectf,( ALuint effect, ALenum param, ALfloat *value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetEffecti,( ALuint effect, ALenum param, ALint *value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetEffectfv,( ALuint effect, ALenum param, ALfloat *values ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetEffectiv,( ALuint effect, ALenum param, ALint *values ))

AL_PROC(_EFX,ALC_EXT_EFX,void,alGenFilters,( ALsizei n, ALuint *filters ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alDeleteFilters,( ALsizei n, ALuint *filters ))
AL_PROC(_EFX,ALC_EXT_EFX,ALboolean,alIsFilter,( ALuint filter ))

AL_PROC(_EFX,ALC_EXT_EFX,void,alFilterf,( ALuint filter, ALenum param, ALfloat value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alFilteri,( ALuint filter, ALenum param, ALint value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alFilterfv,( ALuint filter, ALenum param, ALfloat *values ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alFilteriv,( ALuint filter, ALenum param, ALint *values ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetFilterf,( ALuint filter, ALenum param, ALfloat *value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetFilteri,( ALuint filter, ALenum param, ALint *value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetFilterfv,( ALuint filter, ALenum param, ALfloat *values ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetFilteriv,( ALuint filter, ALenum param, ALint *values ))

AL_PROC(_EFX,ALC_EXT_EFX,void,alGenAuxiliaryEffectSlots,( ALsizei n, ALuint *auxiliaryeffectslots ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alDeleteAuxiliaryEffectSlots,( ALsizei n, ALuint *auxiliaryeffectslots ))
AL_PROC(_EFX,ALC_EXT_EFX,ALboolean,alIsAuxiliaryEffectSlot,( ALuint auxiliaryeffectslot ))

AL_PROC(_EFX,ALC_EXT_EFX,void,alAuxiliaryEffectSlotf,( ALuint auxiliaryeffectslot, ALenum param, ALfloat value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alAuxiliaryEffectSloti,( ALuint auxiliaryeffectslot, ALenum param, ALint value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alAuxiliaryEffectSlotfv,( ALuint auxiliaryeffectslot, ALenum param, ALfloat *values ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alAuxiliaryEffectSlotiv,( ALuint auxiliaryeffectslot, ALenum param, ALint *values ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetAuxiliaryEffectSlotf,( ALuint auxiliaryeffectslot, ALenum param, ALfloat *value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetAuxiliaryEffectSloti,( ALuint auxiliaryeffectslot, ALenum param, ALint *value ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetAuxiliaryEffectSlotfv,( ALuint auxiliaryeffectslot, ALenum param, ALfloat *values ))
AL_PROC(_EFX,ALC_EXT_EFX,void,alGetAuxiliaryEffectSlotiv,( ALuint auxiliaryeffectslot, ALenum param, ALint *values ))

